pluginManagement {
    repositories {
        maven { url = uri('https://maven.aliyun.com/repository/gradle-plugin') }
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri('https://maven.aliyun.com/repository/public') }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = uri('https://jitpack.io') }
        maven { url = uri('https://maven.aliyun.com/repository/public') }
        maven { url = uri('https://maven.aliyun.com/repository/google') }
    }
}

rootProject.name = "Gateway"
include ':app'
